public class MathematicalClass {
    public Integer addition(Integer num1, Integer num2){
        integer sum = num1 + num2;
        return sum;
    }
    public Integer subtraction(Integer num1, Integer num2){
        integer subs = num1 - num2;
        return subs;

    }
    public Integer multiplication(Integer num1, Integer num2){
        integer multi = num1 * num2;
        return multi;

    }
    public Integer division(Integer num1, Integer num2){
        integer div = num1 / num2;
        return div;
    }
    
}
