public  class MyCity {
    // public string favoriteCafe = ' ';
    // public string favoritePark = ' ';
    // public string favoriteMall = ' ';
    // public string favoriteStore = ' ';

    // public string myFavoriteLocations(string city){
    //     System.debug('Most beautiful cafe in my city : ' + favoriteCafe + ' most beautiful park :'
    //     + favoritePark + ' Most beautiful mall : ' + favoriteMall + ' most beautiful store : ' + favoriteStore );  
    //     return city;
    // }

    // public void cityInformation(){
    //    // String country = 'Tanzania';
    //    // String city = 'Zanzibar';
    //    // String dream = 'Gezmek istedigim ulke -> ' + country + ' ve sehir ->' + city;
    //   //  System.debug(dream);

    //     datetime kurulus = Datetime.newInstance(1776, 7, 4, 0, 0, 0);
    //     System.debug('Amerikanin kurulus tarihi : ' + kurulus);
    //     Time gundogumu = Time.newInstance(7, 09, 05, 0);
    //     System.debug('Gun dogumu saati: ' + gundogumu);
    //     date todayHere = date.today();
    //     date ago36months = todayHere.addMonths(-36);
    //     System.debug('Bugunun tarihi ' + todayHere + 've 36 ay oncesinin tarihi ' + ago36months);
    // }
    // public void stringMethod(){
    //     String words = 'I am a salesforce Developer';
    //     System.debug(words);
    //     Boolean containForce = words.contains('force');
    //     System.debug('Does the words contain force ? '+ containForce);
    //     integer howmanyChar = words.length();
    //     System.debug('My sentence has ' + howmanyChar + ' character.');
    //     string wordsInCap = words.toUpperCase();
    //     System.debug('New view is with uppercase => ' + wordsInCap);

    // }
    // public void dateMethod(){
    //     date currentDay = date.today();
    //     System.debug('Bugunun tarihi : ' + currentDay);
    //     Datetime current = Datetime.now();
    //     System.debug('Bugunun tarih ve saati: ' + current);
    //     Datetime later50Hours = current.addHours(50);
    //     System.debug('50 saat sonrasi ' + later50Hours );
    // }
    public void printString(string m, integer n){
       
        for( integer i = 0; i < n; i++){
            system.debug('I am gonna do my best.  ' + i);

        }
       
    }
}
