MathematicalClass result = new MathematicalClass();

Integer sumResult = result.addition(24, 6);
System.debug('The result of addition => ' + sumResult);

integer subsResult = result.subtraction(13, 5);
System.debug('The result of subscription  => ' + subsResult);

integer multiResult = result.multiplication(9, 10);
System.debug('The result of multiplication => ' + multiResult);

integer divResult = result.division(36, 9);
System.debug('The result of division => ' + divResult);